### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [latelylk/pyavaccess#1]
It would be very helpful if you could tag releases as well. This would enable distributions to fetch the package from GitHub instead of PyPI.

Thanks

**Comment by latelylk** [comment]
[I've tagged the latest release and the previous ones as well](https://github.com/latelylk/pyavaccess/releases). Was there anything else I needed to do?

> enabling distributions to retrieve the package from GitHub rather than PyPI

Could you please provide more info about this use case?

**Comment by fabaff** [comment]
Tags at https://github.com/latelylk/pyavaccess/tags are fine. Thanks for that.

There is an small inconvenience with the naming from a packager point of view: `pyproject.toml` says [0.2.0](https://github.com/latelylk/pyavaccess/blob/v0.2.0-alpha/pyproject.toml#L7) but the tag is called [0.2.0-alpha](https://github.com/latelylk/pyavaccess/releases/tag/v0.2.0-alpha). The tags suggests that there will be a new release `0.2.0` as it's currently it's `alpha` while in fact it already `0.2.0`.

**Comment by latelylk** [comment]
Good callout. I have edited the previous releases to be consistent with the versions used on PyPI (0.0.1 0.1.0, 0.2.0). The old tags will be kept for compatibility and future releases will be tagged to match PyPI and the [Python Packaging guidelines](https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers).
